name: Test Fake Steps

on:
  pull_request:
    branches:
      - master

jobs:
  fake-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Log SHA
        run: |
          echo "Commit SHA1?: ${{ github.sha }}"
          echo "Commit SHA2?: ${{ github.event.pull_request.head.sha }} "

      - name: Run fake steps script
        run: |
          pip install requests
          python3 fake_steps.py ${{ github.event.pull_request.head.sha }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
